fun main(){
    print("student Enrollment No.: ")
    val enroll = readLine()!!.toBigInteger()
    print("student Name: ")
    val name = readLine()
    print("student Branch: ")
    val branch = readLine()
    print("student Class: ")
    val cls = readLine()
    print("student Batch: ")
    val batch = readLine()
    print("student College Name: ")
    val cllg_name = readLine()
    print("student University Name: ")
    val uni_name = readLine()
    print("student Age: ")
    val age = readLine()!!.toInt()
    println("\n ***************** \n")
    println("Student's Data: ")
    println("Enrollment No.: $enroll")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $cls")
    println("Batch: $batch")
    println("College Name: $cllg_name")
    println("University Name: $uni_name")
}